// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgMOmIphMMxSePaVfV0hTbPc8gM6SpqOQ',
    appId: '1:234441748902:web:074ae47d12ae8c563edf67',
    messagingSenderId: '234441748902',
    projectId: 'componentes-eca63',
    authDomain: 'componentes-eca63.firebaseapp.com',
    storageBucket: 'componentes-eca63.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7czAhl94Ma5sOzYYI8nA60Q940vmXsSo',
    appId: '1:234441748902:android:9595168ebd9bf96a3edf67',
    messagingSenderId: '234441748902',
    projectId: 'componentes-eca63',
    storageBucket: 'componentes-eca63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC70AYWCDNM0P0um-VP_BEKnOyTH8Fb-uA',
    appId: '1:234441748902:ios:80769b718551317a3edf67',
    messagingSenderId: '234441748902',
    projectId: 'componentes-eca63',
    storageBucket: 'componentes-eca63.appspot.com',
    iosBundleId: 'com.example.practica3',
  );
}
